// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhyewtushjurqwzhpvdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oeWV3dHVzaGp1cnF3emhwdmR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTUzOTgsImV4cCI6MjA2OTA3MTM5OH0.u4T7CkKJa5Q6XjrfotDLXKXlzJVNdbzIEl0k5QSTzEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});